esphome:
  name: nodemcu-2
  on_boot:
    priority: -10
    # ...
    then:
      - if:
          condition:
            binary_sensor.is_off: IR2
          then:
            - mqtt.publish:
                topic: student/CASA0022/ucfnmz0/IR2
                payload: "OFF"
          

    
    
    
    
    


esp8266:
  board: nodemcuv2

# Example configuration entry
    
binary_sensor:
  - id: IR2
    platform: gpio
    filters:
      - delayed_on: 400ms
      - delayed_off: 400ms
      
    pin:
      number: D1
      mode:
        input: true
        pullup: true
      inverted: false
    name: "IR Sensor v2"
    device_class: motion
    on_press:
      then:
        - mqtt.publish:
                topic: student/CASA0022/ucfnmz0/IR2
                payload: "ON"
    
    

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  log_topic: 
    topic: student/CASA0022/ucfnmz0/nodemcu2/log
    level: "DEBUG"
  birth_message:
    topic: student/CASA0022/ucfnmz0/nodemcu2/topic
    payload: online
  will_message:
    topic: student/CASA0022/ucfnmz0/nodemcu2/topic
    payload: offline
    
  on_message:
    - topic: student/CASA0022/ucfnmz0/nodemcu2/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: student/CASA0022/ucfnmz0/nodemcu2/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1
    - topic: student/CASA0022/ucfnmz0/nodemcu2/request
      payload: 'R'
      then: 
        - mqtt.publish:
            topic: student/CASA0022/ucfnmz0/IR_request_2
            payload: !lambda |- 
              return esphome::to_string(id(IR2).state);

  
        
deep_sleep:
  id: deep_sleep_1
  run_duration: 15s
  sleep_duration: 5min
    
# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "c8Tr7xLw/UgyMAotzZQNHK8RguHF+zkz1bus8yJyCkU="

ota:
  password: "a5c273f02bdc7ff91952dbc7207ea1f4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu-2 Fallback Hotspot"
    password: "E7WjS4q7zoke"

captive_portal:
    